### ISSUE TITLE
Small bug in the OWL file (illegal character in the owl:Ontology element)

### ISSUE THREAD

**Issue by florenceclavaud** [lcnetdev/PREMIS#2]
Just to mention that the OWL file (and its version available at https://id.loc.gov/ontologies/premis-3-0-0.rdf) has a  ';' character following the owl:versionInfo element, in the owl:Ontology element; which makes the file not usable as it is.

**Comment by florenceclavaud** [comment]
And there is also an invalid space character at the end of owl:versionIRI/@rdf:resource:
<owl:versionIRI rdf:resource="https://id.loc.gov/ontologies/premis-3-0-0 "/>

**Comment by BertrandCaron** [comment]
Thanks for spotting this Florence. The typos are corrected in Github. Our colleagues at the Library of Congress will update the version id.loc.gov accordingly.
